TK1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import  static
from . import settings
from rest_framework.documentation import include_docs_urls
from allauth.account.views import LoginView, SignupView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    #experiment using allauth
    path('socilalaccounts/', include('allauth.urls')),
    path("login/", LoginView.as_view(), name="llogin"),
    path('docs/', include_docs_urls(title='shop_API')),
    path('',include("barang.urls"), name="barang"),
    path('kupon/', include('kupon.urls'), name='kupon'),
    path('api/', include('api.urls'), name='api'),
    path("ulasan/",include("ulasan.urls"), name="ulasan"),
    path("transaksi/",include("transaksi.urls"), name="transaksi"),
    path("myadmin/", include("myadmin.urls") , name="myadmin"),
    path("", include("timauth.urls") , name="timauth"),
    path("keranjang/",include("keranjang.urls"),name="keranjang"),
    path("transaksicepat/", include("checkout.urls"),name="transaksicepat")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkout/urls.py
from django.urls import path, include
from . import views

app_name = 'checkout'
urlpatterns = [
    path('handle_transaksi/', views.handle_transaksi, name="handle_transaksi"),
    path("submit_transaksi/", views.submit_transaksi, name="submit_transaksi")
]

transaksi/urls.py
from django.urls import path
from . import views

app_name = "transaksi"

urlpatterns = [
    path("history/",views.history_view, name="history"),
    path("checkout/",views.checkout, name="checkout"),
    path("add_transaksi/",views.add_transaksi, name="add_transaksi")
]

checkout/models.py
from django.db import models
from django.contrib.auth.models import User
from keranjang.models import Keranjang, TransaksiBarang
from kupon.models import Kupon

# Create your models here.
class TransaksiCepat(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    barang = models.ManyToManyField(TransaksiBarang)
    kupon = models.ForeignKey(Kupon, on_delete=models.CASCADE, default= None, blank=True, null=True)
    tanggal_beli = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Transaksi cepat milik {self.user} dengan kupon: {self.kupon} pada {self.tanggal_beli}"

transaksi/models.py
from django.db import models
from barang.models import Barang
from kupon.models import Kupon

class Transaksi(models.Model):
    @property
    def get_transaksi(self):
        try:
            return self.barang.harga_barang * (100 - self.kupon.percentage) // 100
        except:
            return self.barang.harga_barang # Biar kuponnya opsional

    nama_pembeli = models.TextField(max_length=50)
    barang = models.ForeignKey(Barang,on_delete=models.PROTECT)
    total_transaksi = get_transaksi
    kupon = models.ForeignKey(Kupon,on_delete=models.PROTECT,null=True, blank=True) # Biar kuponnya opsional
    tanggal_beli = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} - {} @ {}".format(self.nama_pembeli, self.barang, self.tanggal_beli)

    
        

    

checkout/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_object_or_404
from keranjang.models import Keranjang
from .models import TransaksiCepat
from kupon.models import Kupon
from django.contrib.auth.decorators import login_required

@login_required(login_url='/login/')
def submit_transaksi(request):
    keranjang = request.user.keranjang.isi_keranjang.all()
    checkout_list = {
        tb : tb.barang.harga_barang * tb.jumlah for tb in keranjang
    }

    total_harga = 0
    for harga in checkout_list.values():
        total_harga += harga

    context = {
        "total_harga" : total_harga,
        "checkout_list" : checkout_list.items(),
        "checkout_page" : True
    }
    # checkout_list = dictionary {TransaksiBarang : harga total barang itu.}

    return render(request, "transaksicepat.html", context)

@csrf_exempt
def handle_transaksi(request):
    if request.method == "POST" and request.is_ajax():
        failed_items = []
        for transaksi_barang in request.user.keranjang.isi_keranjang.all():
            jumlah_dibeli = transaksi_barang.jumlah
            actual_stock = transaksi_barang.barang.stok_barang
            if jumlah_dibeli > actual_stock:
                failed_items.append(transaksi_barang.barang.nama_barang)

        if len(failed_items) != 0:
            return JsonResponse({"status" : "failed", "failed_items" : failed_items})

        nama_kupon = request.POST["nama_kupon_dipilih"]
        kupon_terpilih_instance = None
        if nama_kupon != "None":
            kupon_terpilih_instance = Kupon.objects.get(name = nama_kupon)
        
        new_transaksi_cepat = TransaksiCepat.objects.create(
            user = request.user,
            kupon = kupon_terpilih_instance
        )
        
        # kurangi stok barang yang dibeli dan tambah ke transaksicepat
        for tb in request.user.keranjang.isi_keranjang.all():
            new_transaksi_cepat.barang.add(tb)
            barang_instance = tb.barang
            barang_instance.stok_barang -= tb.jumlah
            barang_instance.save()

        new_transaksi_cepat.save()

        # kosongkan keranjang si user.
        request.user.keranjang.isi_keranjang.clear()

        return JsonResponse({"status" : "success"})

transaksi/views.py
from django.shortcuts import render, redirect
from .models import Transaksi
from barang.models import Barang
from kupon.models import Kupon
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from checkout.models import TransaksiCepat

def get_total_harga_transaksi(transaksi_cepat):
    total_harga = 0
    for transaksi_barang in transaksi_cepat.barang.all():
        total_harga += transaksi_barang.barang.harga_barang * transaksi_barang.jumlah
    
    if transaksi_cepat.kupon != None:
        return int(total_harga - (total_harga*(100-transaksi_cepat.kupon.percentage)/100))
    else:
        return total_harga

@login_required(login_url='/login/')
def history_view(request):
    transaksi_list = [
        (transaksi_cepat, get_total_harga_transaksi(transaksi_cepat), ", ".join(map(str,transaksi_cepat.barang.all()))) for transaksi_cepat in TransaksiCepat.objects.filter(user = request.user).order_by("-tanggal_beli").all()
    ]
    context = {
        "transaksi_list" : transaksi_list
    }
    return render(request, "history.html", context)

@login_required(login_url='/login/')
def checkout(request):
    if request.method == "POST":
        # Detail barang yang di checkout
        nama_barang = request.POST["nama_barang"]
        harga_barang = request.POST["harga_barang"]
        stok_barang = request.POST["stok_barang"]
        deskripsi_barang = request.POST["deskripsi_barang"]
        
        # Pencarian kupon
        try:
            nama_kupon = request.POST["nama_kupon"] if request.POST["nama_kupon"] else ""
            persentase_kupon = request.POST["persentase_kupon"] if request.POST["persentase_kupon"] else 0
            kupon_list = Kupon.objects.filter(name__icontains = nama_kupon)
            kupon_list = kupon_list.filter(percentage__gte = persentase_kupon)
            kupon_list = kupon_list.filter(kadaluarsa__gte = timezone.now(), min_price__lte = harga_barang) # Check kadaluarsa
        except:
            kupon_list = Kupon.objects.filter(kadaluarsa__gte = timezone.now(), min_price__lte = harga_barang)[:10]
            nama_kupon = ""
            persentase_kupon = ""

        barang_dibeli = Barang.objects.get(
            nama_barang = nama_barang,
            harga_barang = harga_barang,
            stok_barang = stok_barang,
            deskripsi_barang = deskripsi_barang
        )

        # Milih kupon
        try:
            kupon_terpilih = request.POST["kupon_terpilih"].split("---")
            nama_kupon_terpilih = kupon_terpilih[0]
            persentase_kupon_terpilih = kupon_terpilih[1]
            harga_setelah_potongan = int(barang_dibeli.harga_barang * (100-float(persentase_kupon_terpilih)) / 100)
        except:
            nama_kupon_terpilih = ""
            persentase_kupon_terpilih = ""
            harga_setelah_potongan = None

        context = {
            "barang_dibeli" : barang_dibeli,
            "kupon_list" : kupon_list,
            "nama_kupon" : nama_kupon,
            "persentase_kupon" : persentase_kupon,
            "nama_kupon_terpilih" : nama_kupon_terpilih,
            "persentase_kupon_terpilih" : persentase_kupon_terpilih,
            "harga_setelah_potongan" : harga_setelah_potongan
        }

        return render(request, "checkout.html", context)
    else:
        return redirect("barang:index")

def add_transaksi(request):
    if request.method == "POST":
        # Detail barang yang di checkout
        nama_barang = request.POST["nama_barang"]
        harga_barang = request.POST["harga_barang"]
        stok_barang = request.POST["stok_barang"]
        deskripsi_barang = request.POST["deskripsi_barang"]

        # Nama pembeli
        nama_pembeli = request.POST["nama_depan"] + " " + request.POST["nama_belakang"]

        # Barang yang dibeli
        barang_dibeli = Barang.objects.get(
            nama_barang = nama_barang,
            harga_barang = harga_barang,
            stok_barang = stok_barang,
            deskripsi_barang = deskripsi_barang
        )

        # Kupon yang dipilih dan di submit di hidden form
        try:
            nama_kupon_terpilih = request.POST["kupon_terpilih_nama"]
            persentase_kupon_terpilih = request.POST["kupon_terpilih_persentase"]
            kupon_terpilih = Kupon.objects.get(name=nama_kupon_terpilih, percentage = persentase_kupon_terpilih)
        except:
            kupon_terpilih = None

        # Create transaksi
        new_transaksi = Transaksi.objects.create(
            nama_pembeli = nama_pembeli,
            barang = barang_dibeli,
            kupon = kupon_terpilih
        ).save()
        
        barang_dibeli.stok_barang -= 1 # Kurangi jumlah stok 1
        barang_dibeli.save()

    return redirect("barang:index")

transaksi/templates/checkout.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row h-100">
      <div class="col-lg-6 col-sm-12 p-5 d-flex justify-content-center align-items-center">
        <form action="{% url 'transaksi:add_transaksi' %}" method="POST">

            {% csrf_token %}
            <input type="hidden" value="{{barang_dibeli.nama_barang}}" name="nama_barang">
            <input type="hidden" value="{{barang_dibeli.harga_barang}}" name="harga_barang">
            <input type="hidden" value="{{barang_dibeli.stok_barang}}" name="stok_barang">
            <input type="hidden" value="{{barang_dibeli.deskripsi_barang}}" name="deskripsi_barang">

            <input type="hidden" value="{{nama_kupon_terpilih}}" name="kupon_terpilih_nama">
            <input type="hidden" value="{{persentase_kupon_terpilih}}" name="kupon_terpilih_persentase">
          
            <div class="w-100">
            <h4>Nama Depan</h4>
            <input class="form-control" type="text" placeholder="Nama Depan" name="nama_depan" required>
          </div>
          <div class="w-100 my-2">
            <h4>Nama Belakang</h4>
            <input class="form-control" type="text" placeholder="Nama Belakang" name="nama_belakang" required>
          </div>
          <div>
            <h4>Barang dibeli: {{barang_dibeli.nama_barang}}</h4>
          </div>
          
          <div class="mt-4">
              
            {% if harga_setelah_potongan != None %}
                <h3>Biaya yang dikenakan:</h3>
                <h4>Rp. {{harga_setelah_potongan}}</h4>
            {% else %}
                <h3>Biaya yang dikenakan:</h3>
                <h4>Rp. {{barang_dibeli.harga_barang}}</h4>
            {% endif %}
            <input type="submit" class="btn btn-main " value="Bayar Gan">
          </div>
        </form>
      </div>

      <div class="col-lg-6 col-sm-12 px-5 pt-lg-5">
        <form action="{% url 'transaksi:checkout' %}" method="POST" class="d-flex justify-content-center align-items-center flex-column">
            {% csrf_token %}

            <input type="hidden" value="{{barang_dibeli.nama_barang}}" name="nama_barang">
            <input type="hidden" value="{{barang_dibeli.harga_barang}}" name="harga_barang">
            <input type="hidden" value="{{barang_dibeli.stok_barang}}" name="stok_barang">
            <input type="hidden" value="{{barang_dibeli.deskripsi_barang}}" name="deskripsi_barang">
          
            <h2 class="mb-4">Selamatkan uang anda</h2>
          <div class="w-75 my-1">
            <h4>Nama Kupon</h4>
            <input class="form-control" type="text" placeholder="Nama Kupon" name="nama_kupon">
          </div>
          <div class="w-75 my-1">
            <h4>Persentase Kupon</h4>
            <input class="form-control" type="number" placeholder="Persentase Kupon" name="persentase_kupon">
          </div>
          <input type="submit" class="btn btn-main w-75" value="Cari Kupon">

          {% if nama_kupon_terpilih %}
        <p class="m-0 mt-2 p-0">Anda memilih kupon "{{nama_kupon_terpilih}}"</p>
        <h4 class="m-0 p-0">untuk diskon {{persentase_kupon_terpilih}}%</h4>
        {% endif %}

        {% if nama_kupon %}
        <p>Search for: {{nama_kupon}}</p>
        {% endif %}
        
        {% if persentase_kupon %}
        <p>Persentase diatas: {{persentase_kupon}}%</p>
        {% endif %}


        <p class="m-0 p-0 pt-3">Kupon Available:</p>
        <div class="row mt-3">
            {% for kupon in kupon_list %}
                <div class="col-4 d-flex justify-content-center align-items-center flex-column my-1">
                    <button type="submit" value="{{kupon.name}}---{{kupon.percentage}}" name="kupon_terpilih"
                    class="bg-coupon text-light rounded-lg px-2 py-1 text-center d-flex justify-content-center align-items-center flex-column">
                        <p class="m-0 p-0">{{kupon.name}}</p>
                        <p class="m-0 p-0">{{kupon.percentage}}% Off</p>
                    </button>
                </div>
            {% endfor %}
          </div>

        </form>

        
        </div>
      </div>
    </div>
  </div>

{% endblock %}

transaksi/templates/history.html
{% extends 'base.html' %}
{% block content %}
    <div class="container p-2 d-flex justify-content-center align-items-center flex-column">
        {% for transaksi in transaksi_list %}
        <div class="bg-main3 w-75 p-3 border-history my-2" id="transaksi-history-card">
            <div class="row">
                <div class="col-lg-6 col-sm-12 d-flex justify-content-center align-items-start flex-column">
                    <h1 class="m-0 p-0">{{transaksi.0.user.username}}</h1>
                    <p class="m-0 p-0">Barang: {{transaksi.2}}</p>
                </div>
                <div class="col-lg-6 col-sm-12 d-flex justify-content-center align-items-start flex-column">
                    <p class="m-0 p-0">{{transaksi.0.tanggal_beli|date:"Y-m-d / G:i"}}</p>
                    <p class="m-0 p-0">
                        {% if transaksi.0.kupon != None %} 
                            Coupon: {{transaksi.0.kupon.name}} ({{transaksi.0.kupon.percentage}}% off)
                        {% else %}
                            No coupon used
                        {% endif %}
                    </p>
                    <h2 class="m-0 p-0">Rp. {{transaksi.1}},00</h2>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}