TK1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import  static
from . import settings
from rest_framework.documentation import include_docs_urls
from allauth.account.views import LoginView, SignupView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    #experiment using allauth
    path('socilalaccounts/', include('allauth.urls')),
    path("login/", LoginView.as_view(), name="llogin"),
    path('docs/', include_docs_urls(title='shop_API')),
    path('',include("barang.urls"), name="barang"),
    path('kupon/', include('kupon.urls'), name='kupon'),
    path('api/', include('api.urls'), name='api'),
    path("ulasan/",include("ulasan.urls"), name="ulasan"),
    path("transaksi/",include("transaksi.urls"), name="transaksi"),
    path("myadmin/", include("myadmin.urls") , name="myadmin"),
    path("", include("timauth.urls") , name="timauth"),
    path("keranjang/",include("keranjang.urls"),name="keranjang"),
    path("transaksicepat/", include("checkout.urls"),name="transaksicepat")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

barang/urls.py
from django.urls import path, include
from . import views

app_name = 'barang'
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:index>/', views.detail, name="detail")
]

checkout/urls.py
from django.urls import path, include
from . import views

app_name = 'checkout'
urlpatterns = [
    path('handle_transaksi/', views.handle_transaksi, name="handle_transaksi"),
    path("submit_transaksi/", views.submit_transaksi, name="submit_transaksi")
]

keranjang/urls.py
from django.urls import path, include
from . import views

app_name = 'keranjang'
urlpatterns = [
    path('', views.detail, name="detail"),
    path('create/',views.create, name="create"),
    path('reduced/',views.reduced, name="reduced"),
    path('add/',views.add, name="add"),
]

timauth/urls.py
from django.urls import path, include
from .views import signup

app_name = 'timauth'

urlpatterns = [
    path('signup/', signup, name="signup"),
]

transaksi/urls.py
from django.urls import path
from . import views

app_name = "transaksi"

urlpatterns = [
    path("history/",views.history_view, name="history"),
    path("checkout/",views.checkout, name="checkout"),
    path("add_transaksi/",views.add_transaksi, name="add_transaksi")
]

timauth/models.py
from django.db import models

# Create your models here.

timauth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(max_length=20, widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username','password']

class UserSigninForm(UserCreationForm):
    nama_lengkap = forms.CharField()
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ("nama_lengkap","username","email")

timauth/views.py
from django.shortcuts import render, reverse, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from .forms import UserForm, UserSigninForm
from barang.views import index

from keranjang.models import Keranjang
from django.dispatch.dispatcher import receiver
from allauth.account.signals import user_signed_up, user_logged_in

@receiver(user_logged_in)
def user_log_(request, user, **kwargs):
    try:
        Keranjang.objects.get(nama_keranjang = user)
    except:
        Keranjang.objects.create(nama_keranjang = user)
    # Keranjang.objects.create(nama_keranjang = user)

def signup(request):
    context = {
        'form': UserSigninForm
    }
    if request.method == "GET":
        return render(request, "signup.html", context=context)
    if request.method == 'POST':
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        if password1 != password2:
            context['error'] = "Password do not match!"
            return render(request, "signup.html", context=context)
        else:
            username = request.POST['username']
            email = request.POST['email']
            nama_lengkap = request.POST['nama_lengkap'].split()
            nama_depan = nama_lengkap[0]
            nama_belakang = ""
            if(len(nama_lengkap) > 1):
                nama_belakang = " ".join(nama_lengkap[1:])
            user = User.objects.create_user(username=username, password=password1, email=email,
                                    first_name=nama_depan, last_name=nama_belakang)
            # Buat Keranjang baru untuk setiap orang yang daftar.
            Keranjang.objects.create(nama_keranjang = user)

            return redirect('/login/')

timauth/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Meta nyimpen link -->
    <meta name="untukcreate" content="{% url 'keranjang:create' %}">
    <meta name="untukadd" content="{% url 'keranjang:add' %}">
    <meta name="untukkurang" content="{% url 'keranjang:reduced' %}">
    <meta name="untukdetail" content="{% url 'keranjang:detail' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- External CSS -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <!-- Google Fonts API -->
    <link href="https://fonts.googleapis.com/css?family=Share+Tech&display=swap" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <title>TimTam Shop</title>
  </head>
  <body class="bg-main2">

    
  {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-main">
      <a class="navbar-brand" href="{% url 'barang:index' %}">TimTam</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form action="{% url 'barang:index' %}" method="POST" class="form-inline my-2 my-lg-0 ml-auto w-100 d-flex justify-content-center">
          {% csrf_token %}
          <input class="form-control mr-sm-2 w-50" type="search" placeholder="Cari Barang?" aria-label="Search" name="nama_barang">
          <input type="submit" class="btn btn-main2" value="Cari">
        </form>
        <ul class="navbar-nav ml-auto mr-3">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'transaksi:history' %}">History</a>
          </li>
        </ul>
        {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            {% if not checkout_page %}
            <button type="button" class="modal_keranjang btn btn-primary" data-toggle="modal" data-target="#exampleModal">
              Keranjang
            </button>
            {% endif %}
          </li>
        </ul>
        <ul class="navbar-nav ml-xl-4">
          <li class="nav-item">
            hello {{ user.username }}!
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link logout" href="{% url 'logout' %}">Logout</a>
          </li>
        </ul>
        {% else %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link signup" href="{% url 'timauth:signup' %}">Signup</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link login" href="{% url 'account_login' %}">Login</a>
          </li>
        </ul>
      </div>
      {% endif %}
    </nav>
    {% endblock %}
    
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Keranjang</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            
          </div>
          <div class="modal-footer d-flex flex justify-content-between">
              <div class="untuk-harga">

              </div>

              <div class="transaksi-cepat">

              </div>
              <a href="{% url 'checkout:submit_transaksi' %}" class="checkout-ref"><button type="button" class="btn btn-secondary" id="checkout">Checkout</button></a>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    
    {% block content %}
    {% endblock %}
    
    
    <!-- Optional JavaScript -->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

timauth/templates/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="container p-5 d-flex flex-column justify-content-center align-items-center">
    <div class="notification"></div>
    <div class="title">
        <h1>Create A New User</h1>
    </div>
    <div class="accordionlist">
        <p>{{ error }}</p>
        <form action="{% url 'timauth:signup' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="menu">
                    <input type="submit" class="nothing" value="Create Account!">
                <a href="{% url 'account_login' %}">
                    <div class="accordionheader">
                        <p>Already have one?</p>
                    </div>
                </a>
            </div>
        </form>
    </div>
</div>
{% endblock %}